s = set()

b = int(input("enter a number 1st"))
s.add(b)
b = int(input("enter a number 2nd "))
s.add(b)
b = int(input("enter a number 3rd"))
s.add(b)
b = int(input("enter a number 4th"))
s.add(b)
b = int(input("enter a number 5th"))
s.add(b)
b = int(input("enter a number 6th"))
s.add(b)
b = int(input("enter a number 7th"))
s.add(b)
b = int(input("enter a number 8th"))
s.add(b)

print(s)